# Site settings
title: Sally Gillbanks
email: sallygillbanks@gmail.com
url: https://github.com/fruzum
description: "Game Developer | Unity & Unreal Engine | C# and C++. Sally Gillbanks's portfolio showcasing games and interactive projects built with Unity, Unreal Engine, C#, C++, and Unreal Blueprints. Explore my work in game development."
keywords: "Unreal, Unity, Programmer, Blueprints"
skills: "Game Developer: Unity Engine and Unreal Engine"
meta_author: Gillbanks Sally

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "198, 202, 237" #80B3FF
  primary-rgb: "173, 168, 190" #"128,179,255"
  secondary: "162, 132, 151" #FD6E8A
  secondary-dark: "74,48,109" #A2122F

# Footer settings
footer:
  copyright: Sally Gillbanks
  location: Location
  social: Around the web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/fruzum
  - title: linkedin
    url: https://www.linkedin.com/in/sally-gillbanks/
  - title: github
    url: http://github.com/fruzum
  - title: itch
    url: https://fruzum.itch.io/

# Postal address (add as many lines as necessary)
address:
  - line: Wellington, New Zealand
#  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
